# Use an official Python runtime as a parent image
FROM python:latest

RUN apt-get update
RUN apt-get install nano net-tools netstat telnet -y
# Set the working directory to /app
RUN mkdir /service1
WORKDIR /service1
#ADD service1.py /service1/
#ADD index.html /server/

# Copy the current directory contents into the container at /app
COPY . /service1

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 8001

# Define environment variable
#ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]

